### PR TITLE
driver and native driver performance testing commands + refactor

### LINKED ISSUE #21: Support native driver level
The issue is similar to #15, but the driver should be tested using the native protocol (JSON lines over stdin/stdout), [example](https://doc.bblf.sh/writing-a-driver/babelfish-sdk.html#building-an-echo-driver)

### PR DESCRIPTION
**Pull request by lwsanty**
closes #21

Signed-off-by: lwsanty <lwsanty@gmail.com>

---
This change is [Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)

### CODE REVIEW

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 14 of 14 files at r1.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 13 unresolved discussions (waiting on @lwsanty)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-LoQgh9T9BpjjNWYj2bt:b6y287y) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
> ```XML
> 	github.com/cenkalti/backoff v2.1.1+incompatible // indirect
> 	github.com/creachadair/staticfile v0.0.3
> 	github.com/lib/pq v1.2.0 // indirect
> ```

Why it's needed?
___
*[cmd/bblfsh-performance/driver/driver.go, line 112 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQh-ZeAK9DrKcP3Bhk:-LoQh-ZeAK9DrKcP3Bhl:b-1b7ohk) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/driver/driver.go#L112)):*
> ```Go
> 	flags.String("filter-prefix", fileFilterPrefix, "file prefix to be filtered")
> 	flags.StringP("storage", "s", prom.Kind, "storage kind to store the results"+
> 		fmt.Sprintf("(%s, %s, %s)", prom.Kind, influxdb.Kind, file.Kind))
> ```

You can add a description text to `Sprintf` as well.
___
*[cmd/bblfsh-performance/drivernative/drivernative.go, line 103 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjwMP4hdGFFh0OVst:-LoQjwMP4hdGFFh0OVsu:bmkwyjn) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/drivernative/drivernative.go#L103)):*
> ```Go
> 				case <-c:
> 					cancel()
> 					os.Exit(1)
> ```

Looks like a hack. Why do you need this here?
___
*[cmd/bblfsh-performance/drivernative/drivernative.go, line 162 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQk1kmEjfGhsA6rOSk:-LoQk1kmEjfGhsA6rOSl:b-8nrj4w) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/drivernative/drivernative.go#L162)):*
> ```Go
> 	flags.String("filter-prefix", fileFilterPrefix, "file prefix to be filtered")
> 	flags.StringP("storage", "s", prom_pushgateway.Kind, "storage kind to store the results"+
> 		fmt.Sprintf("(%s, %s, %s)", prom_pushgateway.Kind, influxdb.Kind, file.Kind))
> ```

same for the description as in the other command
___
*[cmd/native-driver-performance/main.go, line 25 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjhmaDL_r5MKD7nd0:-LoQjhmaDL_r5MKD7nd1:baxfs13) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L25)):*
> ```Go
> 	fixtures := flag.String("fixtures", "", "path to fixtures directory")
> 	resultsFile := flag.String("results", "", "path to file to store benchmark results")
> 	filterPrefix := flag.String("filter-prefix", "", "file")
> ```

unfinished flag description?
___
*[cmd/native-driver-performance/main.go, line 39 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhTFe91RkzT-AhEzv:-LoQhTFe91RkzT-AhEzw:bmv9lfl) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L39)):*
> ```Go
> 	if err != nil {
> 		log.Infof("cannot get files: %v", err)
> 		os.Exit(1)
> ```

I propose to add a `func run() error` and place all the code there. This way `main` can run the function, check error and `Exit` if necessary (in a single place).
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LoQhlrLDMoNkjLYnLco:bde64wk) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
> ```Go
> 	defer func() {
> 		if err := f.Close(); err != nil {
> 			log.Infof("failed to close file %v: %v", file, err)
> ```

should `Exit(1)` as well? same for `Write` below
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-LoQi4sa78u4XdUJja6J:bnnxi27) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
> ```Go
> 	defer f.Close()
> 
> 	sh := fmt.Sprintf("cat > %[1]s ; chmod +x %[1]s", dst)
> ```

That's an interesting way of uploading files. Will it work for binary files? There should be a better way to copy files to the container.
___
*[docker/docker.go, line 78 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQiGtL1fouoN1clBu-:-LoQiGtL1fouoN1clBu0:b3idh6t) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L78)):*
> ```Go
> 		Context:      ctx,
> 		InputStream:  f,
> 		OutputStream: os.Stdout,
> ```

I propose to redirect `stdout` to `os.Stderr` as well, or it may interfere with CLI output.
___
*[docker/docker.go, line 105 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQiTT1AL6Lkr-EG9N0:-LoQiTT1AL6Lkr-EG9N1:b-2k3ur6) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L105)):*
> ```Go
> 
> 	var buf bytes.Buffer
> 	w := bufio.NewWriter(&buf)
> ```

You don't need `budio.Writer` here. Just pass `&buf` to `stdout`.
___
*[docker/docker.go, line 146 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQimvP5Vnk1LBxul25:-LoQimvP5Vnk1LBxul26:b9ofthp) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L146)):*
> ```Go
> 		RawTerminal:  true,
> 		Tty:          true,
> 		InputStream:  os.Stdin,
> ```

Do we need to redirect `stdin`? And the same suggestion to `stdout` as above.
___
*[docker/docker.go, line 156 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQj5Fu2uVhmjDdJyvt:-LoQj5Fu2uVhmjDdJyvu:b-wdi73e) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L156)):*
> ```Go
> 	inspect, err := d.Pool.Client.InspectExec(exec.ID)
> 	if err != nil {
> 		return errExecFailed.Wrap(err)
> ```

Should it kill/remove exec?
___
*[docker/docker.go, line 238 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjAYy7Kgq3KACHQJ7:-LoQjAYy7Kgq3KACHQJ8:b-q0mpjh) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L238)):*
> ```Go
> 	log.Debugf("waiting for port")
> 	if err := wait(pool, addr); err != nil {
> 		return nil, err
> ```

Should it remove the resource?

**Review by lwsanty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: 10 of 14 files reviewed, 13 unresolved discussions (waiting on @dennwc)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-LoUpLwc4lyqH23vx5gt:bem71) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Why it's needed?
</blockquote></details>

that's weird, `go mod tidy` did not remove it, I removed that deps manually and tried to rebuild binaries, seems to be working o_0 
___
*[cmd/bblfsh-performance/driver/driver.go, line 112 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQh-ZeAK9DrKcP3Bhk:-LoUfZBW7qlhFonKohxV:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/driver/driver.go#L112)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

You can add a description text to `Sprintf` as well.
</blockquote></details>

Done.
___
*[cmd/bblfsh-performance/drivernative/drivernative.go, line 103 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjwMP4hdGFFh0OVst:-LoUfeG_0fJXDi7hQLJA:b-oz3duf) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/drivernative/drivernative.go#L103)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Looks like a hack. Why do you need this here?
</blockquote></details>

It looks like I had some lock during parse request or so, so I could not terminate the process, anyways removed because cannot reproduce it now
Done.
___
*[cmd/bblfsh-performance/drivernative/drivernative.go, line 162 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQk1kmEjfGhsA6rOSk:-LoUg1811da_wTIBmaQ4:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/bblfsh-performance/drivernative/drivernative.go#L162)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

same for the description as in the other command
</blockquote></details>

Done.
___
*[cmd/native-driver-performance/main.go, line 25 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjhmaDL_r5MKD7nd0:-LoUggkADx7K4qY0AuxJ:b1hbrdo) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L25)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

unfinished flag description?
</blockquote></details>


Done.
___
*[cmd/native-driver-performance/main.go, line 39 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhTFe91RkzT-AhEzv:-LoUoH12D3W1yyAADRQ9:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L39)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I propose to add a `func run() error` and place all the code there. This way `main` can run the function, check error and `Exit` if necessary (in a single place).
</blockquote></details>

Done.
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LoUjKnbAk6R9VxqdSo3:b6oc12i) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

should `Exit(1)` as well? same for `Write` below
</blockquote></details>

Done for `Write`, but I've got a little confusion about close. Is it crucial to fail all the process if close has failed?
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-LoUpiBE9V2XXxlnkONq:b-jirdzd) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

That's an interesting way of uploading files. Will it work for binary files? There should be a better way to copy files to the container.
</blockquote></details>

It works for binary files.
I agree that it looks hackish.

As alternative I considered `UploadToContainer` method from API but it deals with tar archives and IMO it's an overkill for our task, I can leave TODO to refactor this part in case we will have a need to upload some more various data to container, but in this case we can always pass volume instead of archive.

About another direction, there was method `CopyFromContainer` but unfortunately it's deprecated.
___
*[docker/docker.go, line 78 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQiGtL1fouoN1clBu-:-LoUko0D50uKMq9HGI6g:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L78)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I propose to redirect `stdout` to `os.Stderr` as well, or it may interfere with CLI output.
</blockquote></details>

Done.
___
*[docker/docker.go, line 105 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQiTT1AL6Lkr-EG9N0:-LoUlCdB1gV2zHD0Q1Am:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L105)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

You don't need `budio.Writer` here. Just pass `&buf` to `stdout`.
</blockquote></details>

Done.
___
*[docker/docker.go, line 146 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQimvP5Vnk1LBxul25:-LoUlRUX7i--3pikLEMs:b-h6zqov) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L146)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Do we need to redirect `stdin`? And the same suggestion to `stdout` as above.
</blockquote></details>

I guess we do not deal with stdin here yet, removed
___
*[docker/docker.go, line 156 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQj5Fu2uVhmjDdJyvt:-LoUmMx18PKQD6cmPmYW:b-nac29u) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L156)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Should it kill/remove exec?
</blockquote></details>

I think no, because:
- I can't see such option in api
- we will fail the test and remove container anyways

am I missing smth?
___
*[docker/docker.go, line 238 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQjAYy7Kgq3KACHQJ7:-LoUoFLUEjQSF9tq04qv:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L238)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Should it remove the resource?
</blockquote></details>

Done.

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r2.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 4 unresolved discussions (waiting on @lwsanty)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-Lo_GFUS0Q09ghNVUKQQ:bclyzlk) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

that's weird, `go mod tidy` did not remove it, I removed that deps manually and tried to rebuild binaries, seems to be working o_0 
</blockquote></details>

Check if you have other uncomitted files locally. `go mod` doesn't use Git, so it will list all the deps from all Go files in the current project.
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-Lo_EwnC56vm4XaFJKFb:b-vwzk8m) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Done for `Write`, but I've got a little confusion about close. Is it crucial to fail all the process if close has failed?
</blockquote></details>

Yes. It usually means the `Flush` on file failed.

For the context, there is a notion that "writes never fail, but flush/fsync may". The reason is that OS buffers most writes to memory and flushes them to disk when the files is closed.
___
*[cmd/native-driver-performance/main.go, line 78 at r2](https://reviewable.io/reviews/bblfsh/performance/22#-Lo_Eg0l6FezMASd-M6t:-Lo_Eg0l6FezMASd-M6u:b-4isdqa) ([raw file](https://github.com/bblfsh/performance/blob/e4e2461621c432e9067785d0cb94372d094803f0/cmd/native-driver-performance/main.go#L78)):*
> ```Go
> 	data, err := json.Marshal(benchmarks)
> 	if err != nil {
> 		return errors.NewKind("failed to marshal results").Wrap(err)
> ```

`errors.New` may be better here (stdlib's `errors`, not `src-d/errors`)
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-Lo_FgE83G1A6KRrKMDr:b-svpztg) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

It works for binary files.
I agree that it looks hackish.

As alternative I considered `UploadToContainer` method from API but it deals with tar archives and IMO it's an overkill for our task, I can leave TODO to refactor this part in case we will have a need to upload some more various data to container, but in this case we can always pass volume instead of archive.

About another direction, there was method `CopyFromContainer` but unfortunately it's deprecated.
</blockquote></details>

TODO sounds fine. Note that Go has a `archive/tar` package that may solve the issues with uploading a tar archive.
___
*[docker/docker.go, line 156 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQj5Fu2uVhmjDdJyvt:-Lo_G4E8Bl7GuCrJd-Bu:bfls7t5) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L156)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

I think no, because:
- I can't see such option in api
- we will fail the test and remove container anyways

am I missing smth?
</blockquote></details>

OK, was not sure if such API exists either, but wanted to make sure.

**Review by lwsanty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 4 unresolved discussions (waiting on @dennwc)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-Loe8zu3AVs6_a2kPgL4:bdp6un) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Check if you have other uncomitted files locally. `go mod` doesn't use Git, so it will list all the deps from all Go files in the current project.
</blockquote></details>

Don't have any, probably I had one for debug before, but now - nope
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LoeB8K769cPDgywmsZ_:bb6un1j) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Yes. It usually means the `Flush` on file failed.

For the context, there is a notion that "writes never fail, but flush/fsync may". The reason is that OS buffers most writes to memory and flushes them to disk when the files is closed.
</blockquote></details>

Done
___
*[cmd/native-driver-performance/main.go, line 78 at r2](https://reviewable.io/reviews/bblfsh/performance/22#-Lo_Eg0l6FezMASd-M6t:-Loe9T_n45wrlaHNyzMp:b-qt3pku) ([raw file](https://github.com/bblfsh/performance/blob/e4e2461621c432e9067785d0cb94372d094803f0/cmd/native-driver-performance/main.go#L78)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

`errors.New` may be better here (stdlib's `errors`, not `src-d/errors`)
</blockquote></details>

I think it does not worth import stdlib's `errors` just for this line of code, or you mean everywhere in the file?
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-LoeBctM0SKG7igRSa0r:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

TODO sounds fine. Note that Go has a `archive/tar` package that may solve the issues with uploading a tar archive.
</blockquote></details>

Done.

**Review by dennwc — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 4 unresolved discussions (waiting on @lwsanty)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-Loecwmw92hCQnhdMM6u:b-gjqtbr) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Don't have any, probably I had one for debug before, but now - nope
</blockquote></details>

We need to find out why it adds this dependency. I don't think we should depend on it.
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LoedTyRBT6X5AtkYr60:bf2c65w) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Done
</blockquote></details>

I don't see any changes here.
___
*[cmd/native-driver-performance/main.go, line 78 at r2](https://reviewable.io/reviews/bblfsh/performance/22#-Lo_Eg0l6FezMASd-M6t:-Loed58N5eAwohXk6uvD:bze9ula) ([raw file](https://github.com/bblfsh/performance/blob/e4e2461621c432e9067785d0cb94372d094803f0/cmd/native-driver-performance/main.go#L78)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

I think it does not worth import stdlib's `errors` just for this line of code, or you mean everywhere in the file?
</blockquote></details>

Yeah, every line that does `errors.NewKind(...).Wrap(err)`. And sorry, I've meant `fmt.Errorf` instead of `errors` here.
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-Loedb-V0hUlclDEj3BK:bj8xljr) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Again, don't see any changes. Have you pushed it to the remote?

**Review by lwsanty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 4 unresolved discussions (waiting on @dennwc)

___
*[go.mod, line 11 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQgh9T9BpjjNWYj2bs:-Loem2NK5Vxbgfx8AZQU:b7x94as) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/go.mod#L11)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

We need to find out why it adds this dependency. I don't think we should depend on it.
</blockquote></details>

`.../go/pkg/mod/github.com/ory/dockertest@v3.3.4+incompatible/dockertest_test.go`
probably the example with dockertest that runs postgres container
___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-Loej-vD5E5fxmehjxCm:b-w85904) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I don't see any changes here.
</blockquote></details>

https://github.com/bblfsh/performance/pull/22/files
changes are visible for me, for example this one
I return both errors to not shadow the original one
```go
defer func() {
		if closeErr := f.Close(); closeErr != nil {
			log.Infof("failed to close file %v: %v", file, closeErr)
			err = fmt.Errorf("err: %v, closeErr: %v", err, closeErr)
		}
	}()
```
___
*[cmd/native-driver-performance/main.go, line 78 at r2](https://reviewable.io/reviews/bblfsh/performance/22#-Lo_Eg0l6FezMASd-M6t:-LoekLSJ69ZHrJs36t_S:b-896fix) ([raw file](https://github.com/bblfsh/performance/blob/e4e2461621c432e9067785d0cb94372d094803f0/cmd/native-driver-performance/main.go#L78)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Yeah, every line that does `errors.NewKind(...).Wrap(err)`. And sorry, I've meant `fmt.Errorf` instead of `errors` here.
</blockquote></details>

Done.
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-LoejI_2D8qQdsc5p52n:b-ozcv22) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

Again, don't see any changes. Have you pushed it to the remote?
</blockquote></details>

Again, https://github.com/bblfsh/performance/pull/22/files
```go
// TODO(lwsanty): use UploadToContainer for more various data
// Upload uploads given file from host to container
// source file's descriptor is used as input stream
// docker executes cat command to redirect this stream to the destination file
func (d *Driver) Upload(ctx context.Context, src, dst string) error {
```

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r3.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 1 unresolved discussion (waiting on @lwsanty)

___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LovBoJh6OvJgocyI--x:b-j0yjop) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

https://github.com/bblfsh/performance/pull/22/files
changes are visible for me, for example this one
I return both errors to not shadow the original one
```go
defer func() {
		if closeErr := f.Close(); closeErr != nil {
			log.Infof("failed to close file %v: %v", file, closeErr)
			err = fmt.Errorf("err: %v, closeErr: %v", err, closeErr)
		}
	}()
```
</blockquote></details>

I would suggest to call the returned error `gerr` (or any other name except `err`). It would be more clear when you override the returned value instead of a local function variable.
___
*[docker/docker.go, line 61 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQi4sa78u4XdUJja6I:-LovCUipA4h9Jsajsf_o:b-g68x59) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/docker/docker.go#L61)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Again, https://github.com/bblfsh/performance/pull/22/files
```go
// TODO(lwsanty): use UploadToContainer for more various data
// Upload uploads given file from host to container
// source file's descriptor is used as input stream
// docker executes cat command to redirect this stream to the destination file
func (d *Driver) Upload(ctx context.Context, src, dst string) error {
```
</blockquote></details>

Sorry, it was a Reviewable failure :(

**Review by lwsanty — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 1 unresolved discussion (waiting on @dennwc)

___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-LoyC3CxEDfXDF1Ubk9X:bb6un1j) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, dennwc (Denys Smirnov) wrote…</i></summary><blockquote>

I would suggest to call the returned error `gerr` (or any other name except `err`). It would be more clear when you override the returned value instead of a local function variable.
</blockquote></details>

Done

**Review by dennwc — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: all files reviewed, 1 unresolved discussion (waiting on @lwsanty)

___
*[cmd/native-driver-performance/main.go, line 86 at r1](https://reviewable.io/reviews/bblfsh/performance/22#-LoQhlrLDMoNkjLYnLcn:-Loz1pVvDYsV10SxRfPZ:b-w727th) ([raw file](https://github.com/bblfsh/performance/blob/6675b152077dab3973550786862402325e7a030b/cmd/native-driver-performance/main.go#L86)):*
<details><summary><i>Previously, lwsanty wrote…</i></summary><blockquote>

Done
</blockquote></details>

Now every error variable in the function is called `gerr`. This is not what I meant. Now you'll need to pick other name instead of `gerr` since the code still uses the same error variable for both the return and for local usage :sweat_smile: 

Please refactor it back to `err`, then manually rename return to `gerr` and set it in `defer` only.

**Review by dennwc — APPROVED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/bblfsh/performance/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
